version: "3"
services:
  master:
    image: locustio/locust
    command: -f /mnt/locust/src/tasks/tasks_set.py --master
    volumes:
      - ./:/mnt/locust
    ports:
      - "8089:8089"
    environment:
      - LOCUST_MODE=master
      - PYTHONPATH=/mnt/locust

  worker:
    image: locustio/locust
    command: -f /mnt/locust/src/tasks/tasks_set.py --worker --master-host master
    volumes:
      - ./:/mnt/locust
    environment:
      - LOCUST_MODE=worker
      - LOCUST_MASTER_HOST=master
      - PYTHONPATH=/mnt/locust
